### ISSUE TITLE
Does Consulpp support other type checks?

### ISSUE THREAD

**Issue by nick2781** [chinuno-usami/Consulpp#1]
Hi,

Thanks for this awesome project.

Does Consulpp support other type checks? Like Http, Script, TTL?

Cuz I just see the TCP check in the test file.

**Comment by chinuno-usami** [comment]
No.I wrote this for my service which only uses tcp connecting.
But it would be easy to extend other check types according to [the documention](https://www.consul.io/docs/agent/checks.html).
By making checks object as interface and construct checks json in the interface.
```c++
class ICheck
{
public:
    ICheck();
    virtual ~ICheck();
    virtual std::string ToJson() = 0;
};
class CHttpCheck: public ICheck
{
public:
    CHttpCheck();
    virtual ~CHttpCheck();
    virtual std::string ToJson();
    void SetId(const std::string& strId);
...
    std::string GetId() const;
...
private:
    std::unique_ptr<CHttpCheckData> m_pData;
};
```

It would be great if you take a pull request. 
Since I have no a consul test environment now. 
And would not implement it in few days.

**Comment by nick2781** [comment]
Thanks a lot, I'll try to add other type checks.
